In [3]:
(train_images,train_labels),(test_images,test_labels)=fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


In [17]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [18]:
label = ["T-shirt/top","Trouser","Pullover","Dress","Coat","Sandal","Shirt","Sneaker","Bag","Ankle boot"]
plt.figure(figsize=(1,1))
plt.imshow(train_images[0], cmap='gray')

In [ ]:
for i in range(10):
    plt.figure(figsize=(1,1))
    plt.imshow(train_images[i],cmap='gray')

In [21]:
train_images[0].shape

(28, 28)

In [58]:
model=Sequential()
model.add(InputLayer(shape=(28,28,1)))
model.add(Conv2D(filters=32,kernel_size=(3,3),activation='relu')) # bydefault activation is  relu 
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(filters=64,kernel_size=(3,3),activation='relu')) # bydefault activation is  relu 
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(filters=128,kernel_size=(3,3),activation='relu')) # bydefault activation is  relu 
model.add(MaxPooling2D((2,2)))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(10,activation='softmax'))
model.summary()

In [35]:
train_images=train_images/255.
#normalize the data
cnn_x_train = train_images.reshape(60000,28,28,1)
#reshaping because our model is expecting input in the shape of 28*2*1
test_images=test_images/255.
#normalize the data
cnn_x_test = test_images.reshape(10000,28,28,1)

In [60]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy')
model.fit(cnn_x_train,train_labels,epochs=10,batch_size = 64,validation_split=0.2)

Epoch 1/10
750/750 [==============================] - 43s 57ms/step - loss: 2.3028 - val_loss: 2.3027
Epoch 2/10
750/750 [==============================] - 29s 38ms/step - loss: 2.3027 - val_loss: 2.3027
Epoch 3/10
750/750 [==============================] - 28s 37ms/step - loss: 2.3027 - val_loss: 2.3027
Epoch 4/10
750/750 [==============================] - 27s 36ms/step - loss: 2.3027 - val_loss: 2.3028
Epoch 5/10
750/750 [==============================] - 28s 37ms/step - loss: 2.3027 - val_loss: 2.3026
Epoch 6/10
750/750 [==============================] - 28s 37ms/step - loss: 2.3027 - val_loss: 2.3027
Epoch 7/10
750/750 [==============================] - 28s 37ms/step - loss: 2.3027 - val_loss: 2.3026
Epoch 8/10
750/750 [==============================] - 28s 37ms/step - loss: 2.3027 - val_loss: 2.3027
Epoch 9/10
750/750 [==============================] - 29s 38ms/step - loss: 2.3027 - val_loss: 2.3028
Epoch 10/10
750/750 [==============================] - 28s 38ms/step - loss: 2.302

In [55]:
yhat = model.predict(cnn_x_test)

array([[0.09983841, 0.10027979, 0.09844364, ..., 0.10053825, 0.10004253,
        0.09938284],
       [0.09983841, 0.10027979, 0.09844364, ..., 0.10053825, 0.10004253,
        0.09938284],
       [0.09983841, 0.10027979, 0.09844364, ..., 0.10053825, 0.10004253,
        0.09938284],
       ...,
       [0.09983841, 0.10027979, 0.09844364, ..., 0.10053825, 0.10004253,
        0.09938284],
       [0.09983841, 0.10027979, 0.09844364, ..., 0.10053825, 0.10004253,
        0.09938284],
       [0.09983841, 0.10027979, 0.09844364, ..., 0.10053825, 0.10004253,
        0.09938284]], dtype=float32)

#### from sklearn.metrics import classification_report, accuracy_score,confusion_matrix
print(classification_report(test_labels,np.argmax(yhat,axis=1),target_names=label))

In [54]:
np.argmax(yhat, axis=1).shape

(10000,)

In [51]:
print(confusion_matrix(test_labels,np.argmax(yhat,axis=1)))

[[   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]]


In [42]:
#change the data- whereever Shirt (label=6) make Tshirt(label=1)
y_train=train_labels.copy()
y_test=train_labels.copy()
y_train[y_train==6]=1
y_test[y_test==6]=1